# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshman_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
